/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author Navin
 */
public enum CSGProp {
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    UNDERGRAD_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    COURSE_SUBHEADER,
    SUBJECT_TEXT,
    NUMBER_TEXT,
    SEMESTER_TEXT,
    YEAR_TEXT,
    TITLE_TEXT,
    INSTRUCTOR_NAME_TEXT,
    INSTRUCTOR_HOME_TEXT,
    EXPORT_DIR_TEXT,
    CHANGE_TEXT,
    TEMPLATE_TEXT,
    DIR_INFO_TEXT,
    SELECT_TEMPLATE_DIRECTORY_TEXT,
    SITE_PAGE_TEXT,
    USE_TEXT,
    NAVBAR_TEXT,
    FILE_TEXT,
    SCRIPT_TEXT,
    PAGE_STYLE_TEXT,
    BANNER_IMAGE_TEXT,
    LEFT_FOOTER_TEXT,
    RIGHT_FOOTER_TEXT,
    STYLESHEET_TEXT,
    STYLESHEET_NOTE,
    RECITATION_TEXT,
    SECTION_TEXT,
    INSTRUCTOR_TEXT,
    DAYTIME_TEXT,
    LOCATION_TEXT,
    TA_TEXT,
    ADDEDIT_TEXT,
    ADDEDIT2_TEXT,
    SECTION_COLON_TEXT,
    INSTRUCTOR_COLON_TEXT,
    DAYTIME_COLON_TEXT,
    LOCATION_COLON_TEXT,
    TA_COLON_TEXT,
    ADDUPDATE_TEXT,
    CLEAR_TEXT,
    SCHEDULE_TEXT,
    CALENDER_BOUNDARIES_TEXT,
    START_MONDAY_TEXT,
    END_FRIDAY_TEXT,
    SCHEDULE_ITEM_TEXT,
    
    TYPE_COL_TEXT,
    DATE_COL_TEXT,
    TITLE_COL_TEXT,
    TOPIC_COL_TEXT,
   
    TYPE_COLON_TEXT,
    DATE_COLON_TEXT,
    TIME_COLON_TEXT,
    TOPIC_COLON_TEXT,
    LINK_COLON_TEXT,
    CRITERIA_COLON_TEXT,
    
    PROJECT_TEXT,
    TEAMS_TEXT,
    COLOR_TEXT,
    TEXT_COLOR_TEXT,
    LINK_TEXT,
    
    NAME_COLON_TEXT,
    COLOR_COLON_TEXT,
    TEXT_COLOR_COLON_TEXT,
    
    STUDENT_TEXT,
    FIRSTNAME_TEXT,
    LASTNAME_TEXT,
    STUDENT_TEAM_TEXT,
    ROLE_TEXT,
    
    FIRSTNAME_COLON_TEXT,
    LASTNAME_COLON_TEXT,
    STUDENT_TEAM_COLON_TEXT,
    ROLE_COLON_TEXT,
    EXPORT_LOCATION_TEXT,
    TEMPLATE_LOCATION_TEXT,
    SUBMIT_TEXT,
    START_TIME_TEXT,
    END_TIME_TEXT,
    UPDATE_TA,
    
    COURSE_TAB,
    TA_TAB,
    REC_TAB,
    SCHEDULE_TAB,
    PROJECT_TAB,
    
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    
    REC_NOT_UNIQUE_TITLE,
    REC_NOT_UNIQUE_MESSAGE,
    REC_MISSING_TITLE,
    REC_MISSING_MESSAGE,
    
    SCH_NOT_UNIQUE_TITLE,
    SCH_NOT_UNIQUE_MESSAGE,
    SCH_MISSING_TITLE,
    SCH_MISSING_MESSAGE,
    
    TEAM_NOT_UNIQUE_TITLE,
    TEAM_NOT_UNIQUE_MESSAGE,
    TEAM_MISSING_TITLE,
    TEAM_MISSING_MESSAGE,
    
    STUDENT_NOT_UNIQUE_TITLE,
    STUDENT_NOT_UNIQUE_MESSAGE,
    STUDENT_MISSING_TITLE,
    STUDENT_MISSING_MESSAGE,
    STUDENT_MISSING_TEAM_TITLE,
    STUDENT_MISSING_TEAM_MESSAGE,
    
    INVALID_DATE_TITLE,
    INVALID_DATE_MESSAGE
}
