/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author Navin
 */
public enum CSGProp {
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    COURSE_SUBHEADER,
    SUBJECT_TEXT,
    NUMBER_TEXT,
    SEMESTER_TEXT,
    YEAR_TEXT,
    TITLE_TEXT,
    INSTRUCTOR_NAME_TEXT,
    INSTRUCTOR_HOME_TEXT,
    EXPORT_DIR_TEXT,
    CHANGE_TEXT,
    TEMPLATE_TEXT,
    DIR_INFO_TEXT,
    SELECT_TEMPLATE_DIRECTORY_TEXT,
    SITE_PAGE_TEXT,
    USE_TEXT,
    NAVBAR_TEXT,
    FILE_TEXT,
    SCRIPT_TEXT,
    PAGE_STYLE_TEXT,
    BANNER_IMAGE_TEXT,
    LEFT_FOOTER_TEXT,
    RIGHT_FOOTER_TEXT,
    STYLESHEET_TEXT,
    STYLESHEET_NOTE,
    RECITATION_TEXT,
    SECTION_TEXT,
    INSTRUCTOR_TEXT,
    DAYTIME_TEXT,
    LOCATION_TEXT,
    TA_TEXT,
    ADDEDIT_TEXT,
    SECTION_COLON_TEXT,
    INSTRUCTOR_COLON_TEXT,
    DAYTIME_COLON_TEXT,
    LOCATION_COLON_TEXT,
    TA_COLON_TEXT,
    ADDUPDATE_TEXT,
    CLEAR_TEXT,
    SCHEDULE_TEXT,
    CALENDER_BOUNDARIES_TEXT,
    START_MONDAY_TEXT,
    END_FRIDAY_TEXT,
    SCHEDULE_ITEM_TEXT,
    
    TYPE_COL_TEXT,
    DATE_COL_TEXT,
    TITLE_COL_TEXT,
    TOPIC_COL_TEXT,
   
    TYPE_COLON_TEXT,
    DATE_COLON_TEXT,
    TIME_COLON_TEXT,
    TOPIC_COLON_TEXT,
    LINK_COLON_TEXT,
    CRITERIA_COLON_TEXT,
    
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE
}
